server:
  port: 7002
eureka:
  instance:
    hostname: eureka-server-centos
  client:
    register-with-eureka: false      #不把本机注册进服务中心
    fetch-registry: false            #不从eureka上获取服务的注册信息
    service-url:
      defaultZone: http://localhost:7002/eureka/


spring:
  redis:
    #数据库索引
    database: 2
    host: 62.234.215.223
    port: 6380
    #连接超时时间
    timeout: 5000
    password: djGX*UN5^Xj93^MY


