server:
  port: 81

eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    instance-id: order81


  client:
    service-url:
      defaultZone: http://localhost:7002/eureka/
#      defaultZone: http://192.168.163.101:7002/eureka/,http://192.168.1.110:7001/eureka/
    registry-fetch-interval-seconds: 5
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true

spring:
  application:
    name: cloud-order-service