server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
        #路由的ID，没有固定的规则但是要求唯一，建议配合服务名
        - id: payment_routh
#          uri: http://localhost:8001
          #匹配后提供的服务的路由地址
          uri: lb://cloud-payment-service
          #断言，路径相匹配的进行路由
          predicates:
            - Path=/payment/get/**
#            - After=2020-05-19T17:58:21.495+08:00[Asia/Shanghai]
#            - Cookie=key,value
#            - Header=X-Request-Id, \d+   #请求头要有X-Request-Id属性并且值为整数的正则表达式
        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**
        - id: ws_routh
          uri: lb:ws://cloud-ws-appliction
          predicates:
            - Path=/ws/**
    loadbalancer:
      ribbon:
        #false 使用ReactiveLoadBalancerClientFilter 进行负载均衡的过滤器
        enabled: true

#配置自定义的rule
cloud-payment-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.li.springcloud.rule.MyGateWayRule
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7002/eureka/
  instance:
    instance-id: gateway9527
    prefer-ip-address: true
    hostname: cloud-gateway-service