server:
  port: 7001

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false      #不把本机注册进服务中心
    fetch-registry: false            #不从eureka上获取服务的注册信息
    service-url:
      defaultZone: http://192.168.163.101:7002/eureka/
  server:
#    #关闭自我保护机制，保证不可用服务被及时剔除
#    enable-self-preservation: false
#    #心跳间隔
#    eviction-interval-timer-in-ms: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

